# Generated by Django 5.0.1 on 2024-02-22 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'Title must be greater than 5 characters')], verbose_name='Заголовок')),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(255, 'Body must be less than 255 characters'), django.core.validators.MinLengthValidator(20, 'Body must be greater than 20 characters')], verbose_name='Описание')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('c', 'created'), ('i', 'in progress'), ('d', 'completed')], default='c', max_length=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
